<?php

namespace modava\article\models\table;

use cheatsheet\Time;
use modava\article\models\query\ArticleCategoryQuery;
use Yii;
use yii\db\ActiveRecord;

class ActicleCategoryTable extends ActiveRecord
{
    const STATUS_PUBLISHED = 1;
    const STATUS_DISABLED = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article_category';
    }

    public static function find()
    {
        return new ArticleCategoryQuery(get_called_class());
    }

    public static function getAllArticleCategory()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-all-article-category';

        $data = $cache->get($key);

        if ($data === false) {
            $data = self::find()->published()->sortDescById()->all();
            $cache->set($key, $data, Time::SECONDS_IN_A_MONTH);
        }

        return $data;
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-all-article-category';
        $cache->delete($key);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-all-article-category';
        $cache->delete($key);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}