<?php


namespace modava\article\components;


use backend\components\MyController;

class MyArticleController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
    protected function getUploadDir()
    {
        $uploadDir = \Yii::$app->getModule('article')->upload_dir;
        return \Yii::getAlias($uploadDir);
    }
}