<?php


namespace modava\article\components;


use backend\components\MyController;

class MyArticleController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}